namespace RubyReloaded.WalletService.Domain.Enums
{
    public enum CurrencyCode
    {
        NGN = 1,
        USD = 2,
        GBP = 3,
        EUR = 4,
        CAD = 5,
        BGN = 6,
        CHF = 7,
        CZK = 8,
        DKK = 9,
        HRK = 10,
        GEL = 11,
        HUF = 12,
        NOK = 13,
        PLN = 14,
        RUB = 15,
        RON = 16,
        SEK = 17,
        TRY = 18,
        UAH = 19,
        AED = 20,
        ILS = 21,
        KES = 22,
        MAD = 23,
        ZAR = 24,
        BRL = 25,
        CLP = 26,
        COP = 27,
        MXN = 28,
        PEN = 29,
        AUD = 30,
        BDT = 31,
        CNY = 32,
        HKD = 33,
        IDR = 34,
        INR = 35,
        JPY = 36,
        MYR = 37,
        NZD = 38,
        PHP = 39,
        PKR = 40,
        SGD = 41,
        KRW = 42,
        LKR = 43,
        THB = 44,
        VND = 45
    }
}
