# ASP.NET Core
# Build and test ASP.NET Core projects targeting the full .NET Core.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- Review

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    #feedsToUse: 'config'
  displayName: 'dotnet restore'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  displayName: "Publish"
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifact: offlineFile