trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - Onyx.ContractService/src/API/Dockerfile.deps
    - Onyx.ContractService/src/API/API.csproj
    - Onyx.ContractService/src/Domain/Domain.csproj
    - Onyx.ContractService/src/Application/Application.csproj
    - Onyx.ContractService/src/Infrastructure/Infrastructure.csproj
    - ReventInject/ReventInject.csproj

pool:
  name: DedicatedPipelines

variables:
- group: shared-keyvault-secrets
- name: azureSubscription
  value: MPN Subscription
- name: dockerImageRegistry
  value: devappcontainers.azurecr.io
- name: dockerImageTag
  value: $[format('{0}-{1}', lower(variables['Build.SourceBranchName']), variables['Build.BuildId'])]
- name: dockerImageName
  value: onyx/contract-service-deps
- name: basePath
  value: Onyx.ContractService
- name: DOCKER_BUILDKIT
  value: 1

steps:
- task: Docker@1
  displayName: Build Docker Image
  inputs:
    azureSubscriptionEndpoint: $(azureSubscription)
    azureContainerRegistry: $(dockerImageRegistry)
    dockerFile: $(basePath)/src/API/Dockerfile.deps
    buildContext: '.'
    useDefaultContext: false
    imageName: $(dockerImageName):$(dockerImageTag)
    includeSourceTags: true
    includeLatestTag: true
    arguments: "--build-arg TOKEN=$(sonarqube-pushToken)"

- task: Docker@1
  displayName: Push Current Version
  inputs:
    azureSubscriptionEndpoint: $(azureSubscription)
    azureContainerRegistry: $(dockerImageRegistry)
    command: Push an image
    imageName: $(dockerImageName):$(dockerImageTag)
    includeSourceTags: true

- task: Docker@1
  displayName: Push Latest
  inputs:
    azureSubscriptionEndpoint: $(azureSubscription)
    azureContainerRegistry: $(dockerImageRegistry)
    command: Push an image
    imageName: $(dockerImageName):latest
    includeSourceTags: true
