{{- if and .Values.keyVault .Values.keyVault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "rubyreloaded-auth.fullname" . }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ include "rubyreloaded-auth.fullname" . }}
    data:
    {{- range .Values.keyVault.secrets }}
    - key: {{ .key }}
      objectName: {{ .key }}
    {{- end }}
    type: Opaque
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "anelloh-{{ .Values.environment }}"
    cloudName: ""
    objects:  |
      array:
        {{- range .Values.keyVault.secrets }}
        - |
          objectName: {{ .key | quote }}
          objectType: secret
          objectVersion: ""
        {{- end }}
    resourceGroup: {{ .Values.environment | quote }}
    subscriptionId: {{ .Values.keyVault.subscriptionId | quote  }}
    tenantId: {{ .Values.keyVault.tenantId | quote  }}
{{ end }}
