trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - RubyReloaded.SubscriptionService/src/API/Dockerfile.deps
      - RubyReloaded.SubscriptionService/src/API/API.csproj
      - RubyReloaded.SubscriptionService/src/Domain/Domain.csproj
      - RubyReloaded.SubscriptionService/src/Application/Application.csproj
      - RubyReloaded.SubscriptionService/src/Infrastructure/Infrastructure.csproj
      - ReventInject/ReventInject.csproj

pool:
  name: DedicatedPipelines

variables:
  - group: shared-keyvault-secrets
  - name: azureSubscription
    value: MPN Subscription
  - name: dockerImageRegistry
    value: devappcontainers.azurecr.io
  - name: dockerImageTag
    value: $(Build.SourceBranchName)-$(Build.BuildId)
  - name: dockerImageName
    value: rubyreloaded/subscription-service-deps
  - name: basePath
    value: RubyReloaded.SubscriptionService
  - name: DOCKER_BUILDKIT
    value: 1

steps:
  - task: Docker@1
    displayName: Build Docker Image
    inputs:
      azureSubscriptionEndpoint: $(azureSubscription)
      azureContainerRegistry: $(dockerImageRegistry)
      dockerFile: $(basePath)/src/API/Dockerfile.deps
      buildContext: "."
      useDefaultContext: false
      imageName: $(dockerImageName):$(dockerImageTag)
      includeSourceTags: true
      includeLatestTag: true
      arguments: "--build-arg TOKEN=$(sonarqube-pushToken)"

  - task: Docker@1
    displayName: Push Current Version
    inputs:
      azureSubscriptionEndpoint: $(azureSubscription)
      azureContainerRegistry: $(dockerImageRegistry)
      command: Push an image
      imageName: $(dockerImageName):$(dockerImageTag)
      includeSourceTags: true

  - task: Docker@1
    displayName: Push Latest
    inputs:
      azureSubscriptionEndpoint: $(azureSubscription)
      azureContainerRegistry: $(dockerImageRegistry)
      command: Push an image
      imageName: $(dockerImageName):latest
      includeSourceTags: true
