# Default values for onyx-contract.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: staging

replicaCount: 1

image:
  repository: devappcontainers.azurecr.io/onyx/contract-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# imagePullSecrets:
# - name: acr-auth

nameOverride: ""
fullnameOverride: ""

envVars: {}
  # key1: value1
  # key2: value2

keyVault:
  enabled: true
  subscriptionId: "<set by pipeline>"
  tenantId: "<set by pipeline>"
  secrets:
  - key: onyx-contract-connectionStringsDefaultConnection
    envVar: ConnectionStrings__DefaultConnection
  - key: onyx-contract-emailUrl
    envVar: Email__Url
  - key: onyx-contract-blobConnectionStringsAccessKey
    envVar: BlobConnectionStrings__AccessKey

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podLabels:
  aadpodidbinding: azure-key-vault-client

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-body-buffer-size: 200m
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
  hosts:
  - host: onyx-contract-staging.reventholdings.com
    paths:
    - path: /
      type: Prefix
  tls:
  - secretName: tls-star-reventholdings-com
    hosts:
    - onyx-contract-staging.reventholdings.com

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
